# Generated by Django 5.1.3 on 2024-11-29 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_report_reports_remove_comments_post_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
