# Generated by Django 5.1.3 on 2024-11-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('advocate', 'Advocate'), ('survivor', 'Survivor'), ('general', 'General User')], default='general', max_length=50),
        ),
    ]
